# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0002_auto_20160509_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
