# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0003_auto_20160509_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='views',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
